FROM node:16-alpine as builder

RUN apk update && apk add build-base autoconf automake libtool pkgconfig nasm

RUN mkdir /app

WORKDIR /app

RUN npm install -g gatsby-cli

COPY ./package*.json ./

RUN npm install --verbose --network-timeout=100000

COPY ./tsconfig.json ./

COPY ./gatsby-config.ts ./

EXPOSE 3333
