FROM node:16-alpine as builder

RUN apk update && apk add build-base autoconf automake libtool pkgconfig nasm

RUN mkdir /app

WORKDIR /app

RUN yarn global add gatsby-cli

COPY ./package*.json ./

RUN yarn install --verbose --network-timeout 100000

COPY ./gatsby-config.ts ./

COPY ./tsconfig.json ./

EXPOSE 3333
